list = ["Ah shit, here we go again.mp3",
"Air Horn.mp3",
"Among Us (Kill).mp3",
"Android Notification.mp3",
"Anime wow.mp3",
"At This Moment He Knew.mp3",
"Awkward Silence.mp3",
"Ayo WTF meme.mp3",
"Bass Boost.mp3",
"Bass drop.mp3",
"Batman Transition.mp3",
"Beep.mp3",
"bing bong.mp3",
"BOI.mp3",
"Bone Crack.mp3",
"Bonk.mp3",
"BOOM BIG SHAQ.mp3",
"Boom.mp3",
"Boris Johnson.mp3",
"bruh chill.mp3",
"Bruh.mp3",
"cartoon running.mp3",
"Censor Beep.mp3",
"COD Let's do this.mp3",
"Come to Birmingham.mp3",
"DAYYYMM.mp3",
"DENIED.mp3",
"Die - Ceeday.mp3",
"Ding.mp3",
"DOLPHIN.mp3",
"don't fcking run away.mp3",
"Door Knocking.mp3",
"DRUM ROLL.mp3",
"dude stop let me go.mp3",
"DUN DUN DUNNN.mp3",
"Enderman Teleport.mp3",
"EVERYBODY PUT YOUR HANDS IN THE AIR.mp3",
"Eww dude WTF.mp3",
"explosion.mp3",
"EZ.mp3",
"FAIL.mp3",
"FALLING.mp3",
"Fart.mp3",
"Fatality.mp3",
"fbi open up.mp3",
"Fck you.mp3",
"Flashback.mp3",
"Fluffing a Duck.mp3",
"fnaf 2 hallway noise.mp3",
"Fortnite Shield Potion.mp3",
"fuck u kid.mp3",
"fuck.mp3",
"Get Noscoped.mp3",
"GET OVER HERE.mp3",
"Get this shit off me.mp3",
"Go Crazy Go Stupid.mp3",
"goku meme.mp3",
"goodnight girl.mp3",
"Growtopia Death Sound.mp3",
"GTA Mission Passed.mp3",
"HA GAY.mp3",
"HA HA.mp3",
"HAAAX.mp3",
"Half Life 1 Scientist.mp3",
"He need some milk.mp3",
"Heartbeat sound.mp3",
"HEAVENLY CHOIR.mp3",
"Hehei Puai.mp3",
"Hello Muthafcka.mp3",
"HELLO THERE.mp3",
"Hi How Are Ya.mp3",
"hit marker.mp3",
"HIT OR MISS.mp3",
"Hitman.mp3",
"Huh.mp3",
"I can-t believe you done this.mp3",
"I GOTTA BAD FEELING ABOUT THIS.mp3",
"ILLUMINATI.mp3",
"im a bad bitch.mp3",
"Im joking stop! STOP!.mp3",
"IM TRIGGERED.mp3",
"Investigations.mp3",
"its a diplodoculas.mp3",
"IVE GOT YOU IN MY SIGHTS.mp3",
"jaaaa.mp3",
"Just do it.mp3",
"KEKW.mp3",
"KungfuShout.mp3",
"LIGHTSABER.mp3",
"Look At This Dude.mp3",
"MarioJump.mp3",
"Meliados vs Escanor.mp3",
"Metal Gear Alert.mp3",
"Minecraft Alpha Damage.mp3",
"Mom get the camera.mp3",
"MONSTER KILL.mp3",
"Mouse Click.mp3",
"NANI.mp3",
"Nice.mp3",
"No God please no.mp3",
"NOPE.mp3",
"Oh no.mp3",
"OHHHHHHHHH.mp3",
"ok.mp3",
"OOF.mp3",
"Ooh, that's kinda small.mp3",
"Oops.mp3",
"Patrick Screaming.mp3",
"Pop.mp3",
"PUNCH.mp3",
"Realistic Gunshot.mp3",
"RECORD SCRATCH.mp3",
"REEEEEE.mp3",
"RELOADING.mp3",
"RUBBER DUCK.mp3",
"SAY WHAT.mp3",
"SCREAM.mp3",
"Sesame Street (Bass Boosted).mp3",
"Sheesh.mp3",
"spicy.mp3",
"SPLAT.mp3",
"Taco Bell Bong.mp3",
"teakettle steam.mp3",
"thankyou.mp3",
"thats pretty good.mp3",
"the fck you say to me you little shit.mp3",
"This is Sparta.mp3",
"THUG LIFE.mp3",
"TOASTY.mp3",
"Tyler1 Driving.mp3",
"Weee- hahaha- oh.mp3",
"Wet fart with reverb.mp3",
"What Are Those.mp3",
"what are you aiming at.mp3",
"What.mp3",
"Why You Bully Me.mp3",
"Why you heff to be mad.mp3",
"Windows XP Shutdown.mp3",
"WOW.mp3",
"WrongBuzzer.mp3",
"YOU SUCK.mp3",
"Your the last one complete the mission.mp3"]

playing = new Audio();

list.forEach(soundName=>{
    button = document.createElement('button')
    button.setAttribute('id',soundName)
    button.setAttribute('class','button')
    button.innerText = soundName.replace('.mp3','')
    button.addEventListener('click',()=>{
        playing.pause()
        const audio = new Audio(`sounds/${soundName}`)
        audio.play()
        playing = audio
    })
    
    document.querySelector('main').appendChild(button)
})